name:                geryon
version:             0.1.0
github:              "javiergarea/geryon"
license:             MIT
author:              "Javier Garea"
maintainer:          "javier.garea@udc.es"
copyright:           "2022 Javier Garea"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/geryon#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  geryon-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geryon

tests:
  geryon-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - geryon
